# Generated by Django 3.2 on 2021-05-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dimension',
            field=models.CharField(default='шт.', max_length=20, verbose_name='Еденица измерения'),
        ),
    ]
