# Generated by Django 3.2 on 2021-05-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
    ]
